name: wallpaper_manager_plus
description: "A Flutter plugin to manage wallpapers on Android"
version: 0.0.1
homepage: https://github.com/sawin0/wallpaper_manager_plus

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.wallpaper_manager_plus
        pluginClass: WallpaperManagerPlus
