name: wallpaper_manager_plus
description: "wallpaper_manager_plus is a Flutter plugin designed to provide developers with an easy-to-use interface for managing device wallpapers on Android. Whether you're building a custom wallpaper app or integrating wallpaper functionality into an existing project, this plugin offers a straightforward solution."
version: 0.0.2
homepage: https://github.com/sawin0/wallpaper_manager_plus

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.wallpaper_manager_plus
        pluginClass: WallpaperManagerPlus
